#
# Makefile
# Jecsan Blanco, 2018-02-02 23:27
#

SpecialNumbers.class: SpecialNumbers.java
	javac SpecialNumbers.java
run: SpecialNumbers.class
	java SpecialNumbers
#interactive	
i:
	java SpecialNumbers -i
clean:
	rm *.class

# vim:ft=make
#
